/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SigningKeyPair {
  private: Buffer
  public: Buffer
}
export declare function generateSigningKeys(ciphersuite: number): SigningKeyPair
